spring.application.name=customer-order-service


# Server
server.port=8080

spring.datasource.url=jdbc:postgresql://orderdb-postgres:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

product.service.base-url=${PRODUCT_SERVICE_URL:http://localhost:8081}

resilience4j.circuitbreaker.instances.productCatalog.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productCatalog.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productCatalog.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productCatalog.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productCatalog.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productCatalog.automaticTransitionFromOpenToHalfOpenEnabled=true